[phases.setup]
nixPkgs = ['nodejs-18_x']

[variables]
NODE_ENV = 'production'

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = [
  'npx prisma generate --schema=./prisma/schema.prisma'
]

[start]
cmd = './scripts/railway-start.sh'